# Generated by Django 5.2.3 on 2025-07-07 11:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
